services:
  bot:
    build: .
    container_name: slonyara2.0
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: ["python", "-m", "telegram_meeting_bot"]
